.TH VMCI 9 "2010\-04\-08" "2010.03.20\-243334" "Open VM Tools"

.SH NAME
vmci \- vmware kernel module

.SH SYNOPSIS
modprobe vmci

.SH DESCRIPTION
This is a Linux kernel device driver module that drives VMware's inter\-VM communication device. The device itself is backed by a PCI\-based virtual hardware implementation, so hotplug or udev should load it at guest boot time in any VMs using hardware version 7.

.SH OPTIONS
vmci has no options.

.SH SEE ALSO
\fIvmware\-checkvm\fR(1)
.br
\fIvmware\-hgfsclient\fR(1)
.br
\fIvmware\-toolbox\fR(1)
.br
\fIvmware\-toolbox\-cmd\fR(1)
.br
\fIvmware\-user\fR(1)
.br
\fIvmware\-xferlogs\fR(1)
.br
\fIlibguestlib\fR(3)
.br
\fIlibvmtools\fR(3)
.br
\fIvmware\-guestd\fR(8)
.br
\fIvmware\-hgfsmounter\fR(8)
.br
\fIvmware\-user\-suid\-wrapper\fR(8)
.br
\fIvmblock\fR(9)
.br
\fIvmhgfs\fR(9)
.br
\fIvmmemctl\fR(9)
.br
\fIvmsock\fR(9)
.br
\fIvmsync\fR(9)
.br
\fIvmxnet\fR(9)
.br
\fIvmxnet3\fR(9)

.SH HOMEPAGE
More information about vmci and the Open VM Tools can be found at <\fIhttp://open\-vm\-tools.sourceforge.net/\fR>.

.SH AUTHOR
Open VM Tools were written by VMware, Inc. <\fIhttp://www.vmware.com/\fR>.
.PP
This manual page was put together from homepage materials by Daniel Baumann <\fIdaniel.baumann@progress-technologies.net\fR>, for the Debian project (but may be used by others).
